import type { ReactElement } from 'react'
import {
  IconAbsence,
  IconAirfield,
  IconCertificate,
  IconCommand,
  IconEtops,
  IconConfidential,
  IconInstructor,
  IconLineCheck,
  IconLowVis,
  IconNotification,
  IconProgress,
  IconRelease,
  IconRemedial,
  IconReport,
  IconRnav,
  IconSimulator,
  IconSkill,
  IconSyllabus,
  IconUprt,
  IconTraining,
} from './Icons'

/** Association entre la clé d'un formulaire et son pictogramme sur l'accueil. */
export const FORM_ICONS: Record<string, (props: { size?: number }) => ReactElement> = {
  'line-check': IconLineCheck,
  training: IconTraining,
  simulator: IconSimulator,
  report: IconReport,
  skill: IconSkill,
  remedial: IconRemedial,
  notification: IconNotification,
  certificate: IconCertificate,
  command: IconCommand,
  rnav: IconRnav,
  confidential: IconConfidential,
  lowvis: IconLowVis,
  etops: IconEtops,
  release: IconRelease,
  instructor: IconInstructor,
  absence: IconAbsence,
  uprt: IconUprt,
  progress: IconProgress,
  airfield: IconAirfield,
  syllabus: IconSyllabus,
}
